name: Validate Changed JSON Files (01–31)

on:
  pull_request:
    paths:
      - '**/[0-3]?[0-9].json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR contents
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to compare with base branch

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Get list of changed files
        id: changed
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed-files.txt
          grep -E '/(0?[1-9]|[12][0-9]|3[01])\.json$' changed-files.txt || true

      - name: Validate changed JSON files
        run: |
          status=0
          for file in $(grep -E '/(0?[1-9]|[12][0-9]|3[01])\.json$' changed-files.txt); do
            echo "Validating $file"
            if jq empty "$file" 2>/dev/null; then
              ajv validate -s validate.schema.json -d "$file" || status=1
            else
              echo "❌ $file has invalid JSON syntax"
              status=1
            fi
          done
          exit $status
