name: Validate Numeric JSON Files (01–31)

on:
  push:
    paths:
      - '**/0[1-9].json'
      - '**/[1-9].json'
      - '**/[12][0-9].json'
      - '**/3[01].json'
  pull_request:
    paths:
      - '**/0[1-9].json'
      - '**/[1-9].json'
      - '**/[12][0-9].json'
      - '**/3[01].json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON files with numeric names (01–31)
        run: |
          find . -regex '.*/\(0[1-9]\|[1-9]\|[12][0-9]\|3[01]\)\.json$' | while read file; do
            echo "Validating $file"
            ajv validate -s validate.schema.json -d "$file"
          done
