name: Validate Changed JSON Files (01–31)

on:
  pull_request:
    paths:
      - '**/0[1-9].json'   # 01–09
      - '**/[1-9].json'    # 1–9
      - '**/1[0-9].json'   # 10–19
      - '**/2[0-9].json'   # 20–29
      - '**/3[01].json'    # 30–31

  push:
    branches:
      - main
    paths:
      - '**/0[1-9].json'
      - '**/[1-9].json'
      - '**/1[0-9].json'
      - '**/2[0-9].json'
      - '**/3[01].json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for diffing

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Get list of changed files
        id: changed
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}
            git diff --name-only origin/${{ github.base_ref }}...HEAD > changed-files.txt
          else
            git diff --name-only HEAD~1 > changed-files.txt
          fi

      - name: Validate changed JSON files
        run: |
          status=0
          grep -E '/(0?[1-9]|1[0-9]|2[0-9]|3[01])\.json$' changed-files.txt | while read file; do
            echo "Validating $file"
            if jq empty "$file" 2>/dev/null; then
              ajv validate -s validate.schema.json -d "$file" || status=1
            else
              echo "❌ $file has invalid JSON syntax"
              status=1
            fi
          done
          exit $status
